spring:
  application:
    name: order-service
  temporal:
    connection:
      target: ${TEMPORAL_ADDRESS:127.0.0.1:7233}
    namespace: default
    workers-auto-discovery:
      packages:
        - com.example.shop.order

server:
  port: ${SERVER_PORT:8080}
